# Generated by Django 2.1.7 on 2019-03-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
