# Generated by Django 2.1.7 on 2019-03-07 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Text', '0004_usertime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTime',
        ),
    ]
