# Generated by Django 2.1.7 on 2019-03-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text', '0005_delete_usertime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpLoadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.CharField(max_length=200)),
            ],
        ),
    ]
