# Generated by Django 2.1.7 on 2019-03-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text', '0006_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='head',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='', max_length=20),
        ),
    ]
